import type { TechStack } from "@/types/tech-stackType";

export const TECH_STACK: TechStack[] = [
  {
    icon: "https://cdn.iconscout.com/icon/free/png-256/free-typescript-icon-svg-download-png-2945272.png",
    key: "typescript",
    title: "TypeScript",
    href: "https://www.typescriptlang.org/",
    categories: ["Language"],
  },
  {
    icon: "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
    key: "js",
    title: "JavaScript",
    href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    categories: ["Language"],
  },
  {
    icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/2048px-Python-logo-notext.svg.png",
    key: "python",
    title: "Python",
    href: "https://www.python.org/",
    categories: ["Language"],
  },

  {
    icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/1822px-ISO_C%2B%2B_Logo.svg.png",
    key: "c++",
    title: "C++",
    href: "https://www.java.com/",
    categories: ["Language"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/Node.js.svg",
    key: "nodejs",
    title: "Node.js",
    href: "https://nodejs.org/",
    categories: ["Runtime Environment"],
  },
  {
    icon: "https://bun.com/logo.svg",
    key: "bun",
    title: "Bun",
    href: "https://bun.sh/",
    categories: ["Runtime Environment"],
  },
  {
    icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
    key: "react",
    title: "React",
    href: "https://react.dev/",
    categories: ["Library", "UI Library"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/png-shadow-512/Next.js.png",
    key: "nextjs2",
    title: "Next.js",
    href: "https://nextjs.org/",
    categories: ["Framework"],
  },
  {
    icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tailwind_CSS_Logo.svg/2560px-Tailwind_CSS_Logo.svg.png",
    key: "tailwindcss",
    title: "Tailwind CSS",
    href: "https://tailwindcss.com/",
    categories: ["Framework"],
  },
  {
    icon: "https://images.seeklogo.com/logo-png/51/2/shadcn-ui-logo-png_seeklogo-519786.png",
    key: "shadcn-ui",
    title: "shadcn/ui",
    href: "https://ui.shadcn.com/",
    categories: ["Library", "Component Library"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/HTML5.svg",
    key: "radixui",
    title: "Radix UI",
    href: "https://www.radix-ui.com/",
    categories: ["Library", "Component Library"],
  },
  {
    icon:"https://icon.icepanel.io/Technology/svg/CSS3.svg",
    key: "motion",
    title: "Motion",
    href: "https://motion.dev/",
    categories: ["Library", "Animation"],
  },
  {
    icon: "https://tanstack.com/images/logos/logo-black.svg",
    key: "tanstack",
    title: "TanStack",
    href: "https://tanstack.com/",
    categories: ["Library"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/FastAPI.svg",
    key: "mobx-state-tree",
    title: "MobX-State-Tree",
    href: "https://mobx-state-tree.js.org/",
    categories: ["State Management"],
  },
  {
    icon:"https://icon.icepanel.io/Technology/svg/Redux.svg",
    key: "redux",
    title: "Redux",
    href: "https://redux.js.org/",
    categories: ["State Management"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/png-shadow-512/Express.png",
    key: "express",
    title: "Ant Design",
    href: "https://ant.design/",
    categories: ["Library", "UI Library"],
  },
  {
    icon: "https://reactrouter.com/_brand/React%20Router%20Brand%20Assets/React%20Router%20Logo/Light.png",
    key: "react-router",
    title: "React Router",
    href: "https://reactrouter.com/",
    categories: ["Library", "Navigation"],
  },
  {
    icon: "https://reactnavigation.org/img/spiro.svg",
    key: "react-navigation",
    title: "React Navigation",
    href: "https://reactnavigation.org/",
    categories: ["Library", "Navigation"],
  },
  {
    icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Git_icon.svg/768px-Git_icon.svg.png",
    key: "git",
    title: "Git",
    href: "https://git-scm.com/",
    categories: ["Version Control"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/png-shadow-512/AWS.png",
    key: "docker",
    title: "Docker",
    href: "https://www.docker.com/",
    categories: ["Containerization"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/Docker.svg",
    key: "docker",
    title: "Docker",
    href: "https://www.docker.com/",
    categories: ["Containerization"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/MySQL.svg",
    key: "mysql",
    title: "MySQL",
    href: "https://www.mysql.com/",
    categories: ["Database"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/PostgresSQL.svg",
    key: "mysql",
    title: "MySQL",
    href: "https://www.mysql.com/",
    categories: ["Database"],
  },
  {
    icon: "https://img.icons8.com/fluent/1200/prisma-orm.jpg",
    key: "mysql",
    title: "MySQL",
    href: "https://www.mysql.com/",
    categories: ["Database"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/MongoDB.svg",
    key: "mongodb",
    title: "MongoDB",
    href: "https://www.mongodb.com/",
    categories: ["Database"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/Redis.svg",
    key: "redis",
    title: "Redis",
    href: "https://redis.io/",
    categories: ["Database"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/png-shadow-512/Socket.io.png",
    key: "figma",
    title: "Figma",
    href: "https://www.figma.com/",
    categories: ["Tools", "Design"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/NGINX.svg",
    key: "ps",
    title: "Adobe Photoshop",
    href: "https://www.adobe.com/vn_en/products/photoshop.html",
    categories: ["Tools", "Design"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/Azure.svg",
    key: "chatgpt",
    title: "ChatGPT",
    href: "https://chatgpt.com/",
    categories: ["Tools", "AI"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/Cloudflare.svg",
    key: "chatgpt",
    title: "ChatGPT",
    href: "https://chatgpt.com/",
    categories: ["Tools", "AI"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/Ubuntu.svg",
    key: "chatgpt",
    title: "ChatGPT",
    href: "https://chatgpt.com/",
    categories: ["Tools", "AI"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/NPM.svg",
    key: "chatgpt",
    title: "ChatGPT",
    href: "https://chatgpt.com/",
    categories: ["Tools", "AI"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/Postman.svg",
    key: "chatgpt",
    title: "ChatGPT",
    href: "https://chatgpt.com/",
    categories: ["Tools", "AI"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/Vite.js.svg",
    key: "chatgpt",
    title: "ChatGPT",
    href: "https://chatgpt.com/",
    categories: ["Tools", "AI"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/Nodemon.svg",
    key: "chatgpt",
    title: "ChatGPT",
    href: "https://chatgpt.com/",
    categories: ["Tools", "AI"],
  },
  {
    icon: "https://icon.icepanel.io/Technology/svg/Visual-Studio-Code-%28VS-Code%29.svg",
    key: "chatgpt",
    title: "ChatGPT",
    href: "https://chatgpt.com/",
    categories: ["Tools", "AI"],
  },
];
